[tool.black]
line-length = 120 # override black's default line-length
exclude = '''
/(
    \.git
  | \.pytest_cache
  | __pycache
  | venv
  | \.venv
  | _build
  | rust
  | build
  | data
)/
'''

[tool.isort]
# make it compatible with black
profile = "black"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-s"
log_cli = "1"
log_cli_level = "DEBUG"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
# log_cli_format = "%(asctime)s - %(filename)s - %(module)s - %(funcName)s - %(lineno)d - %(levelname)s - %(message)s"

log_cli_format = "%(asctime)s.%(msecs)03d %(funcName)s:%(lineno)d %(message)s"
